### ISSUE TITLE
Consider adding `--unstable` to spawn

### ISSUE THREAD

**Issue by fakoua** [TooTallNate/vercel-deno#15]
Consider adding `--unstable` to spawn or some deno modules wont work.

**Comment by TooTallNate** [comment]
Ya sure, I'd like to make it configurable though (probably opt-in) via a build env var and/or config option.

**Comment by TooTallNate** [comment]
See https://github.com/TooTallNate/vercel-deno/pull/18.

**Comment by fakoua** [comment]
> See #18.

Many thanks for your quick response
