### ISSUE TITLE
add --allow-run and --allow-plugin env variables

### ISSUE THREAD

**Issue by divy-work** [TooTallNate/vercel-deno#32]
While trying to open a native plugin and spawning a sub process, vercel-deno does not provide the args for that. Maybe expose an env variable to do so?

**Comment by TooTallNate** [comment]
Might as well use `--allow-all` right? Since Lambda already provides a sandboxed environment. Let me know if #33 will work for you.

**Comment by divy-work** [comment]
Yes, that would be great!
