### ISSUE TITLE
TypeError: ref.startsWith is not a function

### ISSUE THREAD

**Issue by divy-work** [TooTallNate/vercel-deno#34]
Same error but was not fixed by following #16 

Here's my deployment - https://vercel.com/nestdotland/analyzer/8esvs9qzp
and the code - https://github.com/nestdotland/analyzer/blob/master/playground/api/index.ts

**Comment by TooTallNate** [comment]
Thanks for the repro. Should be fixed by #35.

**Comment by TooTallNate** [comment]
Can you try out [`v0.7.0`](https://github.com/TooTallNate/vercel-deno/releases/tag/0.7.0) and let me know if that fixes it for you?
