### ISSUE TITLE
Support Deno v1.4

### ISSUE THREAD

**Issue by ryo-ma** [TooTallNate/vercel-deno#37]
Thank you for the good product.
Will you support Deno version 1.4?

**Comment by TooTallNate** [comment]
I'll update the default version shortly, but note that you can configure a specific version by setting the `DENO_VERSION` build env var in your project's configuration.

**Comment by TooTallNate** [comment]
[v0.7.1](https://github.com/TooTallNate/vercel-deno/releases/tag/0.7.1) uses Deno 1.4.1 by default.

**Comment by ryo-ma** [comment]
Thanks!
