### ISSUE TITLE
Error when i use mongo with the build

### ISSUE THREAD

**Issue by lowray** [TooTallNate/vercel-deno#40]
I'm trying to deploy simple api (deno - opine - mongo),
I get 
```const handler = mod.default
error: Uncaught ReferenceError: default is not defined
const handler = mod.default;
                    ^
    at dev-server.ts:12:21
``` 
 when i use mongo module from https://deno.land/x/mongo@v0.12.1

**Comment by TooTallNate** [comment]
Can you show me your complete code for the API endpoint?

**Comment by lowray** [comment]
```javascript
//app.ts
import { opine } from "https://deno.land/x/opine@0.22.2/mod.ts";
import { MongoClient } from "https://deno.land/x/mongo@v0.12.1/mod.ts";

const client = new MongoClient();
client.connectWithUri("URL");
const db = client.database("NAME");
const users = db.collection<any>("COLLECTION");

const app = opine();

app.use(async (req, res) => {
  res.json(
      await users.find({ name: { $ne: null } })
    )
});



app.listen();
export default app
```
```json
vercel.json
{
    "builds" : [
        {"src" : "*.ts", "use" : "vercel-deno@0.7.1"}
    ],
    "build": {
        "env": {
            "DENO_UNSTABLE" : "true"
        }
    }
}
```

```bash
#bash
>vc dev
error: Uncaught ReferenceError: default is not defined
const handler = mod.default;
                    ^
    at dev-server.ts:12:21
```

**Comment by TooTallNate** [comment]
Thanks for that. I've distilled the issue down to a bug in deno. See https://github.com/denoland/deno/issues/7649.

**Comment by TooTallNate** [comment]
This was fixed in Deno v1.4.5, which is the default version in `vercel-deno@0.7.2`. Please update to this new version and let me know if you have any further issues!

**Comment by lowray** [comment]
There's an error says `error: Uncaught PermissionDenied: access to open a plugin: /home/ma/apps/mopd/.deno_plugins/deno_mongo_f39a1ed8e4b1f4eb61e96bf8794f19af.so, run again with the --allow-plugin flag`
is there any way to configure deno's flags?

**Comment by TooTallNate** [comment]
Can you try `vercel-deno@0.7.3`?

**Comment by lowray** [comment]
Finally, It's working now (on dev server).
This the error i get when i try to deploy it 

![Screenshot from 2020-10-10 01-04-57](https://user-images.githubusercontent.com/54923746/95638490-1b56a480-0a95-11eb-8e22-56d2769e37d3.png)

**Comment by TooTallNate** [comment]
Are you setting the `DEBUG` env var? Try unsetting that.

**Comment by lowray** [comment]
I got this too
![another error](https://user-images.githubusercontent.com/54923746/95646577-19f39f00-0aca-11eb-8d65-3c2b2c27f7ce.png)

**Comment by TooTallNate** [comment]
Looks like the mongo dependency is trying to write to the filesystem. In the serverless function environment, the filesystem is read-only, except for the `/tmp` directory. If possible, try to configure the module to write the necessary files to `/tmp` instead.

**Comment by TooTallNate** [comment]
Btw the issue with using `DEBUG` has been resolved.
