### ISSUE TITLE
Invalid request: `env.DENO_UNSTABLE` should be string.

### ISSUE THREAD

**Issue by Lumca** [TooTallNate/vercel-deno#52]
Hello,

I am trying to run the unstable flag but I am getting "Invalid request: `env.DENO_UNSTABLE` should be string." when pressing deploy button.

This is the vercel.json:
```
{
  "functions": {
    "api/**/*.[jt]s": { "runtime": "vercel-deno@0.7.6" }
  },
  "env": {
    "DENO_UNSTABLE": true
  }
}
```

**Comment by TooTallNate** [comment]
Do `"true"` (as a string), not `true` (as a boolean).

**Comment by Lumca** [comment]
You are right, thank you.
