### ISSUE TITLE
Runtime is broken for Deno version 1.6.x

### ISSUE THREAD

**Issue by Nexxkinn** [TooTallNate/vercel-deno#55]
Running `vercel-deno` runtime works fine for default version, but bumping it to recent version (1.6.3) returns `NO_RESPONSE_FROM_FUNCTION`

log report from vercel:
```
[GET] /

Check file:///var/task/.runtime.ts
error: Read-only file system (os error 30) (for '"/var/task/.deno/gen/file/var/task/.runtime.ts.buildinfo"')
RequestId: df133447-d543-4ad6-b9e0-58b9d0f16d6c Error: Runtime exited with error: exit status 1
Runtime.ExitError
```
Any Idea why? My guess is that they changed their buildinfo in 1.6.x

**Comment by TooTallNate** [comment]
Ya, I haven't had time to look into it yet. It's frustrating that these cache files change so frequently. It's a constant cat and mouse game. Will definitely try to get to it soon, but PR welcome if someone happens to figure out what changed in the meantime.

**Comment by Nexxkinn** [comment]
I heard that they’ll gonna release new version `1.7.0` tomorrow. I’ll try check it out later.

**Comment by christianhaller** [comment]
1.7.2 seems okay

**Comment by TooTallNate** [comment]
Indeed! [1.8.0 works as well](https://vercel-deno-ak5vsjqbb-tootallnate.vercel.app/api/hello). I'm gonna close this as wontfix since the current version of Deno works.
