### ISSUE TITLE
Support the root directory setting

### ISSUE THREAD

**Issue by flobaader** [TooTallNate/vercel-deno#56]
Hi @TooTallNate,

thank you for the nice runtime! I love to see Deno support for Vercel.
I am currently unable to deploy my project, because Vercel fails with the build message:

```
The Root Directory setting is not supported for vercel-deno@0.7.6
```

Do you have any plans to support that setting? We are using a mono-repo at our project and therefore need the `ROOT_PROJECT` settings of Vercel.

Best wishes,

Florian

**Comment by TooTallNate** [comment]
Can you tell me the steps you did to get that error?

**Comment by flobaader** [comment]
Hi @TooTallNate, I do not have the deno files in the root folder of my project, but in a subdirectory. 
Then I need to tell vercel which directory should be the root for this project.
