### ISSUE TITLE
No such device or address

### ISSUE THREAD

**Issue by muazamkamal** [TooTallNate/vercel-deno#6]
With `vercel dev`, version 19.1.1
```
Compile file:///home/muazamkamal/Documents/Projects/api/api/hello.ts
error: Uncaught Error: No such device or address (os error 6)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at Object.openSync ($deno$/ops/fs/open.ts:22:10)
    at Object.openSync ($deno$/files.ts:28:15)
    at file:///home/muazamkamal/.cache/com.vercel.cli/dev/builders/node_modules/vercel-deno/dist/dev-server.ts:16:21
```

But with `vercel deploy`, it works.

I'm new to both Vercel and Deno, and serverless functions as a general. Probably I might have missed something.

**Comment by TooTallNate** [comment]
What operating system are you using?

**Comment by muazamkamal** [comment]
Sorry, forgot to mention it. I'm running Linux.

**Comment by TooTallNate** [comment]
Can you try out [`v0.3.2`](https://github.com/TooTallNate/vercel-deno/releases/tag/0.3.2) and let me know if it's working for you now?
