### ISSUE TITLE
Add ability to configure `--location`

### ISSUE THREAD

**Issue by PaulKinlan** [TooTallNate/vercel-deno#65]
I have a bunch of modules (that I don't have permission to change) that are using relative paths to fetch data from the current origin. In an ideal word I would be able to change this, but I can't :( I do however know the base URL at run time.

I'm relatively new to deno, but my understanding is that we need to be able to set the default location at runtime via `--location` [command line flag](https://deno.land/manual@v1.9.2/runtime/location_api).

p.s, thanks for creating this runtime (very useful)

**Comment by PaulKinlan** [comment]
Oh interesting idea.

That would work for me, and would be rather flexible in the future too.

**Comment by TooTallNate** [comment]
Ok, added the shebang parsing in v0.8.0. For example, [here](https://vercel-deno-6ee21fa9i-tootallnate.vercel.app/api/dump) you can see the "location" object contains the `window.location` that was set [here](https://github.com/TooTallNate/vercel-deno/blob/4844e75a261753012a1f5168e8d3a9d7d2c7e265/api/dump.ts#L1).

Let me know if it works for you!
