### ISSUE TITLE
How to configure DENO_DIR for dynamic imports?

### ISSUE THREAD

**Issue by 5310** [TooTallNate/vercel-deno#79]
Thanks for the Deno runtime! I came running back to Vercel because Deno Deploy doesn't do dynamic imports and vercel-deno is a lifesaver :smile_cat: 

Unfortunately, I still can't get dynamic imports working because I get this runtime error:
`TypeError: Could not create TypeScript compiler cache location: "/var/task/.deno/gen/file/var/task/commands/1"`

I saw that the solution was to simply set the `DENO_DIR` variable to something under `/tmp`. Unfortunately, simply setting that variable either on Vercel's settings or with the hashbang wasn't enough to change the directory.

This is what I have right now as my hashbang, the env var as well as the two includes for files I want to import which work fine:
```sh
#!/usr/bin/env DENO_DIR=/tmp/.deno deno run --include-files ../util/**/* --include-files ../commands/**/*
```

Is there any other way I can configure `DENO_DIR`?

**Comment by TooTallNate** [comment]
I'm not seeing an example that's utilizing dynamic imports, I vaguely recall having some issues making that work in the past, so it's possible that it's not actually possible at the moment. Can you share some example code of what you're trying to do?

> I saw that the solution was to simply set the `DENO_DIR` variable to something under `/tmp`.

I'm curious where you saw this 😄

**Comment by 5310** [comment]
Apologies for forgetting to include the comment where I got the DENO_DIR idea. It was on [this comment](https://github.com/TooTallNate/vercel-deno/issues/64#issuecomment-827129324 on issue #64.

I'll come back with a small demo repo shortly.

**Comment by 5310** [comment]
Example repo created with further description: https://github.com/5310/issue_vercel-deno_dynamic-imports

**Comment by TooTallNate** [comment]
Thanks for that repro. Would like to get this working, will look into it soon.

**Comment by TooTallNate** [comment]
Ok, well it's a simple change in the `bootstrap` file to make it work (right now `DENO_DIR` is always set in that file before invoking deno. I think we can make it only set it by default, and allow to overwrite via env var).

Example: https://vercel-deno-o1u7gi9m0-tootallnate.vercel.app/api/main

You can see in the [Function invocation logs](https://vercel.com/tootallnate/vercel-deno/9r41etCfrZV7iXnYBVq8EsFF5PB7/functions) that the source files are downloaded / compiled at runtime (which leads to a rather slow cold boot):

<img width="616" alt="Screen Shot 2021-08-28 at 7 30 12 PM" src="https://user-images.githubusercontent.com/71256/131236253-2dc8bfcf-c7b5-4daa-b872-c50fb5d92bb9.png">

That said, I'd still like overwriting `DENO_DIR` be supported, so I'll turn this into a proper PR next.

**Comment by 5310** [comment]
I guess a compilation penalty is unavoidable. Honestly, your deploy was fast enough for my use-case still.

Thanks for looking into it so swiftly! Will await that PR :relaxed:

**Comment by 5310** [comment]
My functions are already working dynamically with v1.0 

Thank you again for the fix and ofc for the runtime! :trophy:
